run:
  task: jalan

data:
  dir: /Users/01052711/Desktop/Playground/fache/data/ebe-dataset/evidence_identification_dataset4jalan
  max_len: 128

model:
  arch: cl-tohoku/bert-base-japanese
  dir: /Users/01052711/Desktop/Playground/fache/results/${run.task}/${model.arch}
  classifier_hidden_size: 300

inference:
  batch_size: 16
  n_workers: 1

server:
  port: 12345

hydra:
  run:
    dir: /tmp/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}/outputs
  output_subdir: /tmp/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}